name: "Deploy static helm chart"
description: "Deploy static helm chart"
inputs:
  gcloud_key:
    description: 'Gcloud service account service key (encoded in base64)'
    default: ''
    required: true
  gke_project:
    description: 'Gcloud project'
    required: true
  gke_zone:
    description: 'Gcloud zone'
    required: true
  gke_cluster:
    description: 'GKE cluster'
    required: true

runs:
  using: "composite"
  steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ inputs.gcloud_key }}
        project_id: ${{ inputs.gke_project }}
    - uses: google-github-actions/get-gke-credentials@main
      with:
        cluster_name: ${{ inputs.gke_cluster }}
        location: ${{ inputs.gke_zone }}
        credentials: ${{ inputs.gcloud_key }}
    - name: get cluster credentials
      shell: bash
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $GKE_PROJECT
    - name: deploy
      shell: bash
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm repo add ronasit https://ronasit-charts.storage.googleapis.com
        helm repo update
        echo $CI_PROJECT_NAME
        echo $CHART_VALUES
        helm upgrade --atomic --install ${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG} --version ${CHART_VERSION} -f ${CHART_VALUES:="/dev/null"} --debug \
          --namespace=${CI_PROJECT_NAME} \
          --create-namespace \
          --set fullnameOverride="${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}" \
          --set ingress.hosts[0]=$(echo "${CI_ENVIRONMENT_URL}" | awk -F/ '{print $3}') \
          --set ingress.tls[0].secretName="${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-tls" \
          --set ingress.tls[0].hosts[0]=$(echo "${CI_ENVIRONMENT_URL}" | awk -F/ '{print $3}') \
          --set image.repository="${GKE_PROJECT }/${IMAGE}" \
          --set image.tag="${GITHUB_RUN_NUMBER}" 
