name: "Deploy static helm chart"
description: "Deploy static helm chart"

runs:
  using: "helm"
  steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GCLOUD_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    - uses: google-github-actions/get-gke-credentials@master
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GCLOUD_KEY }}
    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
    - name: get cluster credentials
      run: |
        gcloud container clusters get-credentials $GKE_CLUSTER \
          --zone $GKE_ZONE \
          --project $GKE_PROJECT
    - name: deploy
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        helm repo add ronasit https://ronasit-charts.storage.googleapis.com
        helm repo update
        helm upgrade --atomic --install ${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG} ${CHART_REPO} --version ${CHART_VERSION} -f ${CHART_VALUES:="/dev/null"}
          --namespace=${CI_PROJECT_NAME}
          --create-namespace
          --set fullnameOverride="${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}"
          --set ingress.hosts[0]=$(echo "${CI_ENVIRONMENT_URL}" | awk -F/ '{print $3}')
          --set ingress.tls[0].secretName="${CI_PROJECT_NAME}-${CI_ENVIRONMENT_SLUG}-tls"
          --set ingress.tls[0].hosts[0]=$(echo "${CI_ENVIRONMENT_URL}" | awk -F/ '{print $3}')
          --set image.repository="${GKE_PROJECT }/${IMAGE}"
          --set image.tag="${GITHUB_RUN_NUMBER}"